### PR TITLE
fix loading pkg while setup

### PR DESCRIPTION
**Pull request by Borda**
fix loading package while setup #56

simple testing
```bash
virtualenv ~/Desktop/vEnv_tl -p python3
source ~/Desktop/vEnv_tl/bin/activate
pip install git+https://github.com/Borda/pytorch-lightning.git@fix-setup
```

### CODE REVIEW

**Comment by williamFalcon** [comment]
@Borda i hadn’t noticed the requirements change.

1. test-tube is missing, needs to be added. 
2. numpy is also required. 
3. why is this reading from requirements.txt? requirements.txt should be for devs no? maybe i misunderstood how the setup.py works but i thought convention was: required installs for the pacakge in setup.py, required installs for devs in requirements.txt

**Comment by williamFalcon** [comment]
yeah... just googled and what i mentioned looks correct:

https://www.google.com/amp/s/amp.reddit.com/r/Python/comments/3uzl2a/setuppy_requirementstxt_or_a_combination/

**Comment by williamFalcon** [comment]
and confirmed again here.

https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by Borda** [comment]
https://github.com/williamFalcon/pytorch-lightning/pull/71#issuecomment-519414829 the variable requirements contains all packages from `requirements.txt`
this new list is also not complete and will cause issues in future
```
install_requires=['torch>=1.1.0', 'tqdm', 'test-tube>=0.6.7.6'],
```

**Comment by williamFalcon** [comment]
@borda rolled back the setup.py changes. not sure this fixes the issue, but the package installed fine before when it was setup this way.

I want to keep the project simple and easy to read for researchers, it wasn't obvious what was happening before.

I also want to get back to moving features forward not engineering the package more. Once the install is fixed, I don't want to mess around with CI, setup.py, etc... anymore, don't have the bandwidth to fix issues I already dealt with months ago. The package was already stable and ready for new features :)

**Comment by Borda** [comment]
> I want to keep the project simple and easy to read for researchers, it wasn't obvious what was happening before.

Sure, I agree, I just tried to fix some hidden/potential issues, the `install_requirements` was incomplete even before and it would crash on blank env anyway (it would be fine on Conda, there are some preinstalled packages)

> I also want to get back to moving features forward not engineering the package more. Once the install is fixed, I don't want to mess around with CI, setup.py, etc... anymore, don't have the bandwidth to fix issues I already dealt with months ago. The package was already stable and ready for new features :)

Sure, you may leave the CI issues to me... and focus on features :)

**Comment by williamFalcon** [comment]
> [#71 (comment)](https://github.com/williamFalcon/pytorch-lightning/pull/71#issuecomment-519414829) the variable requirements contains all packages from `requirements.txt`
> this new list is also not complete and will cause issues in future
> 
> ```
> install_requires=['torch>=1.1.0', 'tqdm', 'test-tube>=0.6.7.6'],
> ```
> 
> for example `memory.py` needs `import pandas as pd` but `pandas` is missing in your list

i don't remember if memory was needed for dev or actual install. 
please keep requirements.txt and setup.py separate

In fact that's even how PyTorch officially does it:
https://github.com/pytorch/pytorch/blob/master/setup.py#L769
requirements.txt is for dev deps
setup.py for package deps.

setup.py installs each dep listed AND all of their deps...

**Comment by Borda** [comment]
your package `pytorch_lightning` requires `pandas`, see https://github.com/williamFalcon/pytorch-lightning/blob/master/pytorch_lightning/root_module/memory.py#L10
the only reason why it did not crash yet is that `pandas` is preinstalled on Conda...
Then you need to make a statement that your package supports Conda only or you need to install all requirements first...

**Comment by williamFalcon** [comment]
@Borda like i said, test-tube requires pandas... it gets auto-installed.
but i agree that adding explicit pandas install is a good idea.

**Comment by Borda** [comment]
btw, pls, squash this PR before merging... :) https://github.com/williamFalcon/pytorch-lightning/pull/60#issuecomment-519320043

**Comment by williamFalcon** [comment]
I just noticed the fancy squash button option haha :)

PS. just installed this branch in a conda env from scratch and it works fine. looks fixed now i guess?

**Pull request merged**
