### PR TITLE
fix appveyor

### PR DESCRIPTION
**Pull request by Borda**
there was a formatting issue which made it crash...
TODO: provide mi with your badge link in MD format so I will update it here

### CODE REVIEW

**Comment by Borda** [comment]
@williamFalcon the tests are now passing also on Windows
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  [Build status](https://ci.appveyor.com/project/Borda/pytorch-lightning)

**Comment by Borda** [comment]
@williamFalcon could you provide mi with your badge link in MD format so I will update it here

**Comment by Borda** [comment]
@williamFalcon or we can just fix the config to be passing and add badge later... What do you think?

**Comment by Borda** [comment]
@williamFalcon ^^

**Comment by williamFalcon** [comment]
@Borda looks like the build is still failing in windows.

**Comment by williamFalcon** [comment]
let's keep it as a PR until all the things in the PR work consistently. I don't want to burn time in the next weeks on badges not working :). Need to prioritize research and critical PRs+features.

**Comment by Borda** [comment]
@williamFalcon Have you look at fixed branche not the mater which is missing the fix...

**Comment by Borda** [comment]
@williamFalcon pls see the fixed branch...

**Comment by Borda** [comment]
@williamFalcon pls see the fixed branch...

**Comment by williamFalcon** [comment]
@Borda merged but it's broken on master. I'd rather hide the badge if it's broken bc windows support is not a priority. If it can be fixed today then ok, otherwise let's forget about appveyor

**Pull request merged**
