### PR TITLE
fix for pyTorch 1.1

### LINKED ISSUE #491: IterableDataset breaks 1.1 compatibility
A recently introduced feature unfortunately breaks compability with Pytorch 1.1.0. 

**Describe the bug**
IterableDataset support, introduced in [issue 323](https://github.com/williamFalcon/pytorch-lightning/issues/323), requires Pytorch 1.2.0+.    

**To Reproduce**
In a python environment with Pytorch 1.1.0 do:
import pytorch_lightning

**Expected behavior**
Compatibility with Pytorch 1.1.0. I'm filing it as a bug report rather than a docs fix since the dependency on 1.2.0+ introduced by [issue 323](https://github.com/williamFalcon/pytorch-lightning/issues/323) doesn't seem to be intentional.

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
Follow-up to #546 and #549 Fixes #491

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by Borda** [comment]
now the error is:
```
>       checkpoint = init_checkpoint_callback(logger)
tests/test_a_restore_models.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/utils.py:235: in init_checkpoint_callback
    exp = logger.experiment
pytorch_lightning/logging/test_tube_logger.py:37: in experiment
    rank=self.rank,
.tox/py37/lib/python3.7/site-packages/test_tube/log.py:154: in __init__
    super().__init__(log_dir=log_dir, *args, **kwargs)
.tox/py37/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py:199: in __init__
    self._get_file_writer()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <test_tube.log.Experiment object at 0x7f533d7c8b70>
[1m    def _get_file_writer(self):
        """Returns the default FileWriter instance. Recreates it if closed."""
        if self.rank > 0:
            return TTDummyFileWriter()
    
        if self.all_writers is None or self.file_writer is None:
>           if self.purge_step is not None:
E           AttributeError: 'Experiment' object has no attribute 'purge_step'
.tox/py37/lib/python3.7/site-packages/test_tube/log.py:504: AttributeError
```

**Comment by williamFalcon** [comment]
@Borda that’s a test tube error. maybe submit a quick PR there?

**Comment by Borda** [comment]
well, I was confused because `test-tube` does not have PyTorch in [requirements](https://github.com/williamFalcon/test-tube/blob/master/requirements.txt)

**Comment by williamFalcon** [comment]
true. but test-tube is a subclass of summarywriter

**Comment by Borda** [comment]
@jeffling @neggert @Ir1d anyone wants to make a fix on `test-tube`? :)

**Comment by Borda** [comment]
@williamFalcon it seems that the fix in helps for crashing but somehow it makes run test on `tests/test_cpu_models.py::test_early_stopping_cpu_model ` too long and this is Travis output:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

**Comment by williamFalcon** [comment]
@Borda 0.7.4 pushed!

**Comment by williamFalcon** [comment]
@Borda looks like test-tube install has a bug

**Pull request merged**
