### PR TITLE
add package info

### PR DESCRIPTION
**Pull request by Borda**
reaction to #358 and re-opening #359

It would be fine to make a homepage for example from the main README file, as Github offers
see: https://guides.github.com/features/pages/
it is about %min and couple clicks... :)

### CODE REVIEW

**Comment by Borda** [comment]
@williamFalcon could you please add WIP app which would block merging unfinished PR... Thx
see: https://github.com/marketplace/wip

**Comment by Borda** [comment]
the package is still deeply linked on `test-tube` see:
```
from test_tube import HyperOptArgumentParser
from test_tube import Experiment
```

**Comment by williamFalcon** [comment]
awesome. could u rebase master for tests?

did you try pip install -e .?

**Comment by Borda** [comment]
it still does not work :( I check the `scikit-learn` and `scikit-image` and they are not using `buildins` package which somehow is part of `future` so it is a but strange...

**Comment by Borda** [comment]
@williamFalcon any idea why the tests are failing?
```
'gpus_param_tests' not found in `markers` configuration option
```

**Comment by williamFalcon** [comment]
@neggert @Ir1d @ jeffling @shubham anyone want to PR review this?

**Comment by Borda** [comment]
@Ir1d it is a consequence of one of the past decision (https://github.com/williamFalcon/pytorch-lightning/issues/36) to cut examples from the package and keep the `torch_ligthning` independent on workflows like mlflow/test-tube/... and/but examples use `test-tube`

**Comment by Borda** [comment]
@Ir1d anyway missing `test_tube` is not related to this PR since it was not touched in requirements... :)

**Comment by Borda** [comment]
@williamFalcon \ping

**Comment by neggert** [comment]
Looks good. Any thoughts on using the [extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) functionality in setuptools to handle optional testtube/mlflow/cometml dependencies?

**Pull request merged**
