### PR TITLE
Expectopatronum implement #89

### PR DESCRIPTION
**Pull request by williamFalcon**

### CODE REVIEW

**Comment by williamFalcon** [comment]
turned out to be a non-trivial PR haha. tests just passed on GPUs, so we're good to go to merge this. Feel free to take a look through it @expectopatronum

**Comment by expectopatronum** [comment]
You are welcome! Just a minor question: Why is my handle not showing up as a contributor in the files I worked on?

**Comment by williamFalcon** [comment]
fixed! apparently multiple author info gets lost in a squash and merge... bad ui lol. anyhow, i made the changes

**Comment by expectopatronum** [comment]
Thanks so much! Might not seem important but it was one of my first pull
requests :)

**Comment by williamFalcon** [comment]
congrats! i think it’s super important either wsy :)

Would love to keep getting your contributions as you find things you want to add!

**Comment by neggert** [comment]
@williamFalcon  @expectopatronum Nice work, but I have what might be a dumb question. What's the recommended pattern to actually get the test results out? Looking at the code, it looks like the only thing that happens with the results is that they're sent to tqdm.

**Comment by williamFalcon** [comment]
log them using self.experiment

**Pull request merged**
