### PR TITLE
Use pytest tmpdir fixture 

### PR DESCRIPTION
**Pull request by neggert**
As mentioned in #463, replace manually creating and deleting save directories with the [pytest tmpdir](http://doc.pytest.org/en/latest/tmpdir.html) feature. This eliminates the need to manually clear out directories.

Right now, I've just done this for one of the test files. I want to get some feedback on the change before I spend the time to do the rest of them. @williamFalcon @Borda LMK if you agree that this is a good idea and I'll go ahead and do the rest.

### CODE REVIEW

**Comment by neggert** [comment]
Ping @williamFalcon @Borda any thoughts before I go ahead and update the rest of the tests?

**Comment by Borda** [comment]
I would use Unittests - https://docs.python.org/3/library/unittest.html where you can define some action on start and end, in this case, create temp folder and remove at the end, for example:
```
import os
import unittest
import uuid
import shutils

class TestCPUModels(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = os.path.join(os.path.dirname(__file__), uuid.uuid4().hex)
        os.mkdir(self.tmp_dir)

   def test_early_stopping_cpu_model():
       ...

    def tearDown(self):
        shutils.rmtree(self.tmp_dir)
```

**Comment by williamFalcon** [comment]
@neggert sorry, can't look at this carefully until next week!

**Comment by Borda** [comment]
@williamFalcon see the doc of unittests, it says "The setUp() and tearDown() methods allow you to define instructions that will be executed before and after each test method. They are covered in more detail in the section Organizing test code."
in contrast, there is "setUpClass() - A class method called before tests in an individual class are run. setUpClass is called with the class as the only argument and must be decorated as a classmethod()" and "tearDownClass() - A class method called after tests in an individual class have run. tearDownClass is called with the class as the only argument and must be decorated as a classmethod()"
so it will generate a unique temp folder for each test method... :)

**Comment by neggert** [comment]
@Borda pytest has [similar functionality](https://docs.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code). No need to swap out our entire testing framework. I prefer pytest over unittest anyway.

Here I'm using a fixture that is built-in to pytest that does what you're describing. Pytest generates and deletes a temp folder for you.

**Comment by Borda** [comment]
@neggert it is not about swapping framework, unittest is just another functionality as well as doctests... I would call pytest as an ecosystem... where unit-tests belongs :)
btw, you probably missed the link...

**Comment by neggert** [comment]
I guess I'm not clear on why you're suggesting using unittest when we already have this functionality from our existing test framework. Maybe I'm missing your point.

I think the thing you're suggesting we use in unittest is _exactly_ what this PR does using our existing pytest framework.

**Comment by williamFalcon** [comment]
@neggert @Borda let's come back to this after the documentation and coverage is back up to speed.

In the meantime let's go with the solution proposed by @neggert while we look deeper into @Borda 's option.

**Comment by neggert** [comment]
Sounds good. I'll go ahead and update the rest of the tests.

**Comment by neggert** [comment]
@williamFalcon I think this is ready to go. I don't have a GPU that can run the AMP tests, so I'd appreciate a double-check on those. 

There's also something strange going on with the Comet logger test, but I'm not sure if it's related to this PR.

**Comment by neggert** [comment]
ping @williamFalcon. I think this is ready to merge.

**Comment by williamFalcon** [comment]
@neggert sorry, just getting back online. mind rebasing?

**Comment by neggert** [comment]
Fixed the conflicts. Also figured out what's going on with the CometML logger. I'd like to leave that for a separate PR, if you don't mind.

**Pull request merged**
