### PR TITLE
Update find_packages in setup.py

### PR DESCRIPTION
**Pull request by gregunz**
Following discussion in #36 

Fix `find_packages` which included tests and examples as packages.

### CODE REVIEW

**Comment by williamFalcon** [comment]
@gregunz 
Also need to update readme and docs about running demos

**Comment by gregunz** [comment]
Could you point out what are the changes to do in the readme and the docs (did not see any imports of theses (tests, examples) packages) ?
Moreover the link "this template" [here](https://williamfalcon.github.io/pytorch-lightning/examples/Examples/) is 404.

If you point me where to start I can look into this asap (possibly this weekend or on Monday).

**Comment by williamFalcon** [comment]
in the readme, look at the section on running demos. Those should link to examples folder as well. that folder has readmes about demos which might break if that folder is missing.  

could be that it works fine, but please doible check this because broken demos cause a lot of questions haha

**Comment by williamFalcon** [comment]
I agree that this is not great for module resolution, but this way will break a lot of things. I've made the change in #388 by changing the folder name to scope it for pl.

Leaving tests as is for now

**Comment by gregunz** [comment]
About `tests`:

Just beware you are shipping a **package** named "tests" to anyone to anyone using your library.

I don't see why simply excluding it from the shipped PyPI package "will break a lot of things". Could you be explicit ?

About `examples`:

If you really want to ship them with your package, "pl_examples" seems fine, but why not simply having them inside the directory "pytorch-lightning" ?

**Comment by williamFalcon** [comment]
@Borda any input on this?

**Comment by Borda** [comment]
I would keep examples and tests as part of the project but do not distribute them as package... So I would exclude both...
The only argument to put tests to the package could be something like `python setup.py test` which would run all pytest tests... =)

**Pull request closed without merging**
