### PR TITLE
CI buils with minimal and latest requirements

### LINKED ISSUE #462: CI builds with min & max versions
We have a quite a wide range of supported version but they are not properly tested, so I would like to extend/update CI to be built with minimal and maximal versions defined in requirements.

The limitations now are that Travis build already takes about 20min and adding more test configuration would make finishing it even slower... I was recently [playing](https://github.com/Borda/py_sample-project/blob/master/.github/workflows/python-project.yml) with GitHub Actions Workflow (I have joined the beta program and they should be released quite soon) and it seems to be quite convenient... I would prepare such testing, but I need @williamFalcon to joint GitHub Action :)

Another alternative would it do it in CircleCI, but GitHub Action has an advantage that it simply supports all three main platforms - Linux, xOS and Win

### PR DESCRIPTION
**Pull request by Borda**
This PR aims at testing compatibility with minimal and lates package versions from requirements

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/williamFalcon/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?
Fixes #462 #519. Reaction to #491.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by Borda** [comment]
@williamFalcon the test won't pass since it requires changes n the code but with this update, we are able to see in future PRs if it really fixes the PyTorch back-compatibility...

**Comment by Borda** [comment]
@williamFalcon conflicts resolved...

**Comment by Borda** [comment]
also solves #519 and others who ask why some specific version is needed :)

**Comment by williamFalcon** [comment]
@Borda if i merge this the tests will fail. Will you update the code?

**Comment by Borda** [comment]
I would leave code fixing for another PR as we try to keep the PR simple and just one purpose...

**Comment by lemairecarl** [comment]
numpy 1.16.4 is not available on my platform, so I can't install pytorch-lightning using pip.

Are you planning to get this on Pypi soon?
Thanks!

**Comment by Borda** [comment]
@lemairecarl it will be in next release and also you can install it with `pip` from `master`...

**Pull request merged**
