### PR TITLE
Fix testing for mac OS

### PR DESCRIPTION
**Pull request by Borda**
reaction to #390 in particular https://github.com/williamFalcon/pytorch-lightning/pull/390#issuecomment-543986713

### CODE REVIEW

**Comment by Borda** [comment]
@williamFalcon could you restart build https://travis-ci.org/williamFalcon/pytorch-lightning/jobs/600354259 thx

**Comment by williamFalcon** [comment]
@Borda build says error now :(

**Comment by Borda** [comment]
just running the master on my Travis and it seems that the OSx image does not boot...
https://travis-ci.org/Borda/pytorch-lightning/jobs/600592000
which is nothing we can do, just report an issue to Travis...

**Comment by Borda** [comment]
well, now it runs so there can be something with too many queued OSx jobs
see Travis status - https://www.traviscistatus.com/

**Pull request merged**
