### PR TITLE
Enable any ML experiment tracking framework

### LINKED ISSUE #47: Enable any ML experiment tracking framework
People seem to have strong preferences for either using MLFlow, test-tube, polyaxon, etc...

Let's just add generic support for whatever people want to use.  I don't know if generic support is possible, but each can easily be supported individually.  

To make this work we'd need to:
- change the logging to be non test-tube specific. Logging only happens in 2 places (train and validation completion).  
- Each call to log needs to be process-safe. Meaning when using distributed only rank=0 will log.
- the experiment param in Trainer will need to be generalized (signature the same), to take any logger.   

I think that's all that's needed to add this support.   

Any suggestions and takers for working on this integration?   
@Borda @alok

### PR DESCRIPTION
**Pull request by neggert**
This PR implements a generic base class for loggers / experiment tracking frameworks, along with loggers for test tube and MLFlow, as discussed in #47 .

This isn't quite ready to go yet, but I wanted to get some eyes on it early.

ToDo:

- [x] Run (and fix) tests that require GPUs
- [x] Write docstrings
- [x] Update documentation
- [x] Figure out how to handle optional mlflow dependency

It would be very helpful if someone with access to a system with multiple V100s could try running the test suite. I'm seeing some tests hang, and I'm not sure if it's an issue with our cluster or the code.

Resolves #47

### CODE REVIEW

**Comment by williamFalcon** [comment]
Looking good! won't have a chance to look at it deeply until after ICLR deadline

**Comment by neggert** [comment]
@williamFalcon I think this is ready for review now. If you don't mind, I'd like to leave #241 for a separate PR.

**Comment by williamFalcon** [comment]
@neggert looks good at a glance. I'll look at it carefully wed pm after the ICLR deadline

**Comment by williamFalcon** [comment]
@neggert sorry about that, could you fix the merge issues?  i wanted to get the renaming done for this next version.

**Comment by neggert** [comment]
@williamFalcon Fixed!

**Comment by williamFalcon** [comment]
@neggert 
GPU tests fail here:
```
__________________________________________________________________________________ test_running_test_pretrained_model_ddp __________________________________________________________________________________

    def test_running_test_pretrained_model_ddp():
        """Verify test() on pretrained model"""
        if not can_run_gpu_test():
            return

        hparams = get_hparams()
        model = LightningTestModel(hparams)

        save_dir = init_save_dir()

        # exp file to get meta
        logger = get_test_tube_logger(False)
        logger.log_hyperparams(hparams)
        logger.save()

        # exp file to get weights
        checkpoint = ModelCheckpoint(save_dir)

        trainer_options = dict(
            show_progress_bar=False,
            max_nb_epochs=1,
            train_percent_check=0.4,
            val_percent_check=0.2,
            checkpoint_callback=checkpoint,
            logger=logger,
            gpus=[0, 1],
            distributed_backend='ddp'
        )

        # fit model
        trainer = Trainer(**trainer_options)
        result = trainer.fit(model)

        # correct result and ok accuracy
        assert result == 1, 'training failed to complete'
>       pretrained_model = load_model(logger, save_dir, on_gpu=True, module_class=LightningTestModel)

tests/test_models.py:159:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

exp = <pytorch_lightning.logging.test_tube_logger.TestTubeLogger object at 0x7feaf332bc88>, save_dir = '/home/waf251/Developer/pytorch-lightning/tests/save_dir', on_gpu = True
module_class = <class 'pytorch_lightning.testing.lm_test_module.LightningTestModel'>

    def load_model(exp, save_dir, on_gpu, module_class=LightningTemplateModel):

        # load trained model
>       tags_path = exp.get_data_path(exp.name, exp.version)
E       AttributeError: 'TestTubeLogger' object has no attribute 'get_data_path'

tests/test_models.py:1414: AttributeError
```

**Comment by williamFalcon** [comment]
It's useful to have the path where logs are being saved

**Comment by williamFalcon** [comment]
@neggert can you also add a tensorboard logger using PyTorch summaryWriter? we don't need to force people into using test-tube :)

**Comment by neggert** [comment]
I think the test got messed up somewhere in the merging process. `load_model` should be getting called as `load_model(logger.experiment, ...)`, which is what I have in the last version I pushed. Fixed now.

Getting the log path isn't generally applicable, as some loggers like MLFlow can push logs to a server rather than storing them locally. I'd rather the user access logger-specific data like that by reaching into the underlying logger (e.g. `logger.experiment` for test tube). Does that work for you?

Agree on the Tensorboard logger, but I'm not super-familiar with SummaryWriter. Happy to pick it up, but would you mind deferring that to a later PR?

**Comment by williamFalcon** [comment]
got it. makes sense for both points

**Pull request merged**
