### PR TITLE
find actual minimal requirements

### PR DESCRIPTION
**Pull request by Borda**
## What does this PR do?
Find the minimal requirements that let tests pass. In follow-up PR we shall recover back compatibility with PyTorch 1.1 and 1.2

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by Borda** [comment]
@williamFalcon I think that this is an important step to let all other work on this project smoothly going...

**Comment by williamFalcon** [comment]
@Borda sorry we can't do this. We need to recover 1.1 and 1.2 as the most immediate priority

**Comment by Borda** [comment]
I understand, I just propose to do it step by step, not in a single large effort... so the next one is lower to 1.2 with all test passing and then 1.1...

**Comment by williamFalcon** [comment]
ok that makes sense. Can we prioritize that for now? The next release will need to be pushed back if we can't support 1.1 or 1.2.

**Comment by Borda** [comment]
> ok that makes sense.

well, I thought that  you merge it, but instead, you closed it :disappointed: 

> Can we prioritize that for now? The next release will need to be pushed back if we can't support 1.1 or 1.2.

just working on it...

**Pull request closed without merging**
