### PR TITLE
Fix callback metrics for non-Tensor types

### PR DESCRIPTION
**Pull request by ctlaltdefeat**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/williamFalcon/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Fixes issue where metrics of primitive type (float, int, etc.) were causing an issue with logging.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by awaelchli** [comment]
Why can't travis import IterableDataset and how is it related to this PR?

**Comment by Borda** [comment]
@awaelchli pls rebase to actual master...

**Comment by awaelchli** [comment]
@Borda I think only the OP can do that but yes, it explains the error. thanks.

**Comment by williamFalcon** [comment]
@ctlaltdefeat hi! mind rebasing today so we can merge into master?

**Comment by williamFalcon** [comment]
@ctlaltdefeat ummm you might have merged instead? maybe it's easier to clone master fresh and resubmit the PR? Can't approve a PR with 103 file changes

**Comment by ctlaltdefeat** [comment]
@williamFalcon done

**Pull request closed without merging**
