### PR TITLE
Minor imports cleaning

### PR DESCRIPTION
**Pull request by Borda**
some minor code cleaning and switching to relative imports inside the package

- minor code cleaning
- using relative imports in pkg
- reorganise imports to be 1) buildins 2) third-party 3) own
- remove unused imports

### CODE REVIEW

**Comment by Borda** [comment]
the test is passing, but somehow the check is not updated... @williamFalcon 
https://travis-ci.org/williamFalcon/pytorch-lightning/builds/600620693

**Comment by williamFalcon** [comment]
Thanks for the PR. As I've mentioned before, I want to avoid relative imports. Please change to absolute imports and I can review again.

**Comment by Borda** [comment]
Sorry, completely forgot about the relative imports...

**Comment by williamFalcon** [comment]
In addition, added a significant refactor to help avoid conflicts with multiple PRs and for clarity. Feel free to make the header changes there!

**Comment by Borda** [comment]
I would stay now with the minor cleansing so the PR is not so large...
btw, rebased and dropped relative imports ^^ @williamFalcon

**Pull request merged**
