### PR TITLE
add tags argument to MLFlowLogger

### LINKED ISSUE #297: Pass experiment tags to MLFlowLogger
**Is your feature request related to a problem? Please describe.**
When using MLFlowLogger, I'm unable to easily set experiment tags, like username or run name.

**Describe the solution you'd like**
Add parameter `tags=None` which is passed to `MLFlowLogger`. Tags will be passed to `create_run` method

**Describe alternatives you've considered**
Manually hack logger, get experiment from it and set tag there

If you don't see any drawbacks, I can make a PR

### PR DESCRIPTION
**Pull request by festeh**
## What does this PR do?
Fixes #297 
Adds `tags` parameter to `MLFlowLogger` and passes it to `create_run`

### CODE REVIEW

**Comment by williamFalcon** [comment]
should't we just pass in **kwargs?

**Comment by festeh** [comment]
I'm not sure which problem it would solve. Furthermore, user may want to pass `artifact_location` to `create_experiment` via **kwargs - this'll break `create_run` if this argument would be also passed there. Could you provide an insight why using **kwargs would be better?

**Comment by williamFalcon** [comment]
i’m not familiar with mlflow logger, but generally it’s better to pass **kwargs instead of picking and choosing what to pass in. 

someone will 100% ask for one of those other parameters sooner or later...

**Comment by williamFalcon** [comment]
I'll merge this for now, because i want to get this small release out but we can circle back to this later

**Comment by neggert** [comment]
FWIW, I prefer the tags argument over kwargs.

**Pull request merged**
