### PR TITLE
Logger consistency

### LINKED ISSUE #396: MLFlow Logger Docs: MLFlowLogger has no attribute experiment

### PR DESCRIPTION
**Pull request by ceyzaguirre4**
# Before submitting

- Was this discussed/approved via a Github issue? Discussed in [#396](https://github.com/williamFalcon/pytorch-lightning/issues/396)
- Did you read the [contributor guideline](https://github.com/williamFalcon/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)? YES
- Did you make sure to update the docs?   YES
- Did you write any new necessary tests?  (None were necesary)

## What does this PR do?
Fixes #396.

### CODE REVIEW

**Comment by ceyzaguirre4** [comment]
This PR integrates PR #376 and solves an inconsistency with the docs concerning MLFlowLogger's attributes

**Comment by williamFalcon** [comment]
awesome. could you rebase master? test pipeline is back up, so we can merge this when all tests pass. 

@neggert should we keep it consistent and make every logger do self.logger.experiment?

**Comment by neggert** [comment]
I envisioned accessing the experiment/client directly as a kind of escape hatch for edge cases that the `LightningLoggerBase` abstraction doesn't cover. I kind of wanted to keep them named differently intentionally, since they don't behave the same. An `mlflow.Client` had a very different set of methods that a `testtube.Experiment`, so you're going to need to dig into the docs to use it anyway. That said, I wouldn't strongly object to this change.

I think the real long-term solution is to improve the base abstraction so most users don't have to drop down into the lower-level logger.

**Comment by williamFalcon** [comment]
@neggert i don't think it's a good move to try to replicate the interface for each logger... as they have a ton of functionality. We don't want to be in the business of forwarding API calls to the logger's exact API call.

Let's keep it consistent across every logger so users don't have to remember one more thing (ie: logger.experiment always). 

I also would also think about the edge cases backwards. The reason the abstraction exists is so that Trainer can do the correct logging no matter what the logger is. So, Trainer is actually the edge case. Other than that, the user should have full control of the self.logger.experiment and refer to the original docs for guidance.

**Comment by williamFalcon** [comment]
@neggert i don't think it's a good move to try to replicate the interface for each logger... as they have a ton of functionality. We don't want to be in the business of forwarding API calls to the logger's exact API call.

Let's keep it consistent across every logger so users don't have to remember one more thing (ie: logger.experiment always). 

I also would also think about the edge cases backwards. The reason the abstraction exists is so that Trainer can do the correct logging no matter what the logger is. So, Trainer is actually the edge case. Other than that, the user should have full control of the self.logger.experiment and refer to the original docs for guidance.

**Pull request merged**
