### PR TITLE
[WIP] Fix wrong example paths in README.md

### PR DESCRIPTION
**Pull request by heytitle**
# Before submitting

- Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
nope, this PR is a do improvement.

## What does this PR do?
as far as I know, there is no issue related to this fix.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.   

## Did you have fun?
yeah.

### CODE REVIEW

**Comment by heytitle** [comment]
@Borda indeed, there are a couple more. I'm going to create a issue for that and fix them there.

**Comment by Borda** [comment]
@heytitle I think that you do not need an issue if this PR was also created without an issue :) let's keep the flow simple :)

**Comment by heytitle** [comment]
alright, I'll let you know when I'm done.

**Comment by Borda** [comment]
@heytitle pls, put "WIP" to the PR name until it is done, thx

**Comment by heytitle** [comment]
is there anything we have to do here? I'm asking because it's done but the title has been changed to `WIP`.

**Comment by Borda** [comment]
We agreed to fix also other wrong paths example -> pl_example

**Pull request merged**
