### PR TITLE
rename trainer modules, drop `_mixin`

### PR DESCRIPTION
**Pull request by Borda**
##  What does this PR do?
I would continue in rename in trainer package, follow-up #548 
It is a breaking change but I do not think that anyone is using the Mixin classes directly...

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by Borda** [comment]
@neggert ^^ @williamFalcon

**Comment by williamFalcon** [comment]
@Borda rebase?

**Comment by Borda** [comment]
@williamFalcon done :]

**Comment by Borda** [comment]
@williamFalcon done :]

**Comment by Borda** [comment]
@williamFalcon done :]

**Comment by neggert** [comment]
No strong opinion on this change. Doesn't look like it breaks anything.

**Pull request merged**
