### PR TITLE
Cut-out examples

### PR DESCRIPTION
**Pull request by Borda**
Cutting out the examples from the main package
Also, apply relative imports inside the package
Related to #36

### CODE REVIEW

**Comment by williamFalcon** [comment]
Ran checks on GPU. All looks good.

```bash
collected 16 items

tests/test_models.py::test_amp_gpu_ddp PASSED                                                                    [  6%]
tests/test_models.py::test_cpu_slurm_save_load PASSED                                                            [ 12%]
tests/test_models.py::test_loading_meta_tags PASSED                                                              [ 18%]
tests/test_models.py::test_dp_output_reduce PASSED                                                               [ 25%]
tests/test_models.py::test_model_saving_loading PASSED                                                           [ 31%]
tests/test_models.py::test_model_freeze_unfreeze PASSED                                                          [ 37%]
tests/test_models.py::test_amp_gpu_ddp_slurm_managed PASSED                                                      [ 43%]
tests/test_models.py::test_early_stopping_cpu_model PASSED                                                       [ 50%]
tests/test_models.py::test_cpu_model_with_amp PASSED                                                             [ 56%]
tests/test_models.py::test_cpu_model PASSED                                                                      [ 62%]
tests/test_models.py::test_all_features_cpu_model PASSED                                                         [ 68%]
tests/test_models.py::test_single_gpu_model PASSED                                                               [ 75%]
tests/test_models.py::test_multi_gpu_model_dp PASSED                                                             [ 81%]
tests/test_models.py::test_amp_gpu_dp PASSED                                                                     [ 87%]
tests/test_models.py::test_multi_gpu_model_ddp PASSED                                                            [ 93%]
tests/test_models.py::test_ddp_sampler_error PASSED                                                              [100%]

=================================================== warnings summary ===================================================
```

**Comment by williamFalcon** [comment]
Awesome commit! Thanks for contributing!

**Comment by davzha** [comment]
Adding relative imports to the examples leads to the following error message for me:

Traceback (most recent call last):
  File "single_cpu_template.py", line 16, in <module>
    from .lightning_module_template import LightningTemplateModel
ModuleNotFoundError: No module named '__main__.lightning_module_template'; '__main__' is not a package

**Comment by Borda** [comment]
good point @davzha, I will and the normal import for examples here https://github.com/williamFalcon/pytorch-lightning/pull/44

**Pull request merged**
