### PR TITLE
Fix incorrect warning for DistributedSampler.

### PR DESCRIPTION
**Pull request by sai-prasanna**
Check whether `dataloader.sampler` is an instance of DistributedSampler instead of the `dataloader` itself.

### CODE REVIEW

**Comment by williamFalcon** [comment]
@sai-prasanna interesting! Why is this better?

**Comment by sai-prasanna** [comment]
I got the warning even while I implemented a dataloader which uses DistributedSampler. The problem I think is each validation dataloader is a subclass of DataLoader, but is not an instance of `DistributedSampler`.

It will make sense to check whether the attribute `.sampler` is an instance of `DistributedSampler`.

Or am I missing something obvious 😅?

**Comment by Borda** [comment]
I do not think a method like `.sampler` can be `DistributedSampler`, it should be class/instance...

**Comment by sai-prasanna** [comment]
> I do not think a method like `.sampler` can be `DistributedSampler`, it should be class/instance...

https://pytorch.org/docs/stable/_modules/torch/utils/data/dataloader.html#DataLoader

I don't get you, Pytorch Dataloader classes set their sampler with a Sampler object. Or does the DataLoader get wrapped into another object somewhere in the lightning workflow?

**Comment by williamFalcon** [comment]
lightning does nothing to the dataloader. i think it makes sense but need to test it out before merging. i feel like there might have been a reason we did it the way it is right now, but i have to think back.

**Pull request closed without merging**
