### PR TITLE
fix req. in setup

### PR DESCRIPTION
**Pull request by Borda**
addressing missing numpy, #56

### CODE REVIEW

**Comment by williamFalcon** [comment]
@Borda probably need to rebase master on this to get the pep8 changes fixes

**Comment by williamFalcon** [comment]
Applied your patch to a different PR, want to make sure the cloners are stable before I log off for a bit haha.

@Borda awesome work making the testing and code quality more robust in the package! looking forward to facilitating your contributions!

**Comment by Borda** [comment]
the commit is equal to the one in #67 and #68 so I do not understand what was wrong, but never mind...

**Comment by williamFalcon** [comment]
yeah it’s exactly the same. it just had build errors from pep8 lines i messed up. so i did a quick fix on master. 

wanted to get this stuff done bc i’ll be traveling and mostly offline for the next week, so i didn’t want the clone version of the repo to be broken

**Comment by Borda** [comment]
ok, then if you need something so fast (Europe has evening/night at that time) I would recommend doing the correction in the original PR, then creating a couple of new ones which are almost equal... It may be less chaotic and easier to navigate in past project activities ;)

**Comment by williamFalcon** [comment]
good point. will do next time!

enjoy your evening!

**Comment by Borda** [comment]
also, I would say that seeing in git history multiple commits in a row with an equal comment (e.g. 7x "added single gpu train test") does not make a nice impression about the development (very fast and not very conceptual)... for this I would recommend to squash them or do this as a micro-feature development in a branch and then merge it locally as a single commit :]
Overall, I like scikit-learn/image approach where each PR is merged as a single commit to the git history is clear and easy to track/follow, not seeing merge commit across branches...
@williamFalcon ^^

**Pull request closed without merging**
