### PR TITLE
Simplify variables: step, epoch, max_epochs, min_epochs

### PR DESCRIPTION
**Pull request by elliotwaite**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/williamFalcon/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?
Fixes https://github.com/williamFalcon/pytorch-lightning/issues/584.

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by awaelchli** [comment]
It was not changed [here](https://github.com/williamFalcon/pytorch-lightning/blob/58cc6e13b9999161a526b83063c983750e6553b1/pytorch_lightning/trainer/training_loop.py#L167) for example.

**Comment by elliotwaite** [comment]
> It was not changed [here](https://github.com/williamFalcon/pytorch-lightning/blob/58cc6e13b9999161a526b83063c983750e6553b1/pytorch_lightning/trainer/training_loop.py#L167) for example.

This change only addressed changing all `max_num_epochs` to `max_epochs`. Perhaps @Borda can help us out here, he worked on a previous change (https://github.com/williamFalcon/pytorch-lightning/pull/567) that addressed the switch from `max_nb_epochs` to `max_num_epochs` while preserving backward compatibility.

@Borda, any suggestions?

**Comment by Borda** [comment]
it should be change there too and propagate the change across system...
for back compatibility, add a `property` with the `max_nb_epochs` and dedicated warning
```
@poperty
def max_nb_epochs(self):
    """
    .. warning:: Deprecated... will be removed...
    """
    warn("Depredated... will be removed...", DeprecationWarning)
    return self.max_epochs
```
@elliotwaite @awaelchli willing to prepare follow-up PR?

**Comment by elliotwaite** [comment]
Thanks, @Borda. Created a PR: https://github.com/williamFalcon/pytorch-lightning/pull/613

**Pull request merged**
