### PR TITLE
Refactor test modules

### PR DESCRIPTION
**Pull request by neggert**
There was a lot of code duplication in the various test modules. This PR creates a base class that contains most of the duplicated code. Modules used for testing now inherit from that base class, then add extra methods via mixins, which eliminates most of the duplication. This should make maintaining and writing new test cases easier in the future.

For example, if we want to test a `LightningModule` with`test_step` and `test_end` implemented, but no validation, we can just do

```python
class CurrentTestModel(LightningTestMixin, LightningTestModelBase):
    pass
model = CurrentTestModel(hparams)
```

A couple other minor changes along the way:
* Modified how `Trainer.__is_overriden` works so that it functions correctly with more complicated inheritance. It now compares sub-class code to the original `LightingModule` code, rather than the sub-class's direct parent, which is what `super` gives you.
* Found, fixed, and added a new test for a bug that would occur when calling `test` on a model with no `val_dataloader`

### CODE REVIEW

**Comment by williamFalcon** [comment]
@neggert this is brilliant :)  thanks for simplifying this! mind deconflicting?

**Comment by neggert** [comment]
@williamFalcon Rebased and fixed the conflicts. Also did a little more work. Editing the original message to reflect the new stuff.

**Comment by williamFalcon** [comment]
@neggert cool mixins. I'm torn about the mixins. While I agree they're a nice clean solution, it seems like it will make it harder for your non-engineer to add tests when contributing. Since Lightning code is designed to be readable by non-engineers, I'm not sure whether it overcomplicates things.

Maybe the way to overcome this is to document the mixins in the test README?

Any thoughts on that?

**Comment by neggert** [comment]
Hey, sorry for vanishing. I think in the long run this will be simpler for non-engineers (and maintainers), but yes, the docs should be updated. Looks like that README is getting a bit out of date anyway. Might be worth giving some thought to how tests are organized. It looks like at the moment, everything is just getting crammed into `test_model.py`.

**Pull request merged**
