### PR TITLE
add batch types as List[torch.Tensor] and Dict[key: torch.Tensor]

### PR DESCRIPTION
**Pull request by c00k1ez**
Hi!
Firstly I have to say thanks for great library. It is very useful and helps me on my researches but when I tried to create some custom batches like {'tokens': torch.Tensor, 'head_symbols': torch.Tensor, 'tail_symbols': torch.Tensor} I had error, so I tried to fix it.

### CODE REVIEW

**Comment by williamFalcon** [comment]
I'm sorry, i don't understand. How does 
```python
{'tokens': torch.Tensor, 'head_symbols': torch.Tensor, 'tail_symbols': torch.Tensor}
```
not work?

In addition, any updates here have to work with DDP, DP and CPU

**Comment by williamFalcon** [comment]
@c00k1ez also, make sure to chat about this with me first in github issues so we can agree on the fix before doing a PR :)

**Comment by williamFalcon** [comment]
I can't approve this PR until I think about this for a bit. I also need to see your example code of what you're trying to do and the error you got.

**Comment by c00k1ez** [comment]
@williamFalcon ok, I will make Issue when go to work station. Maybe I was wrong :)

**Comment by williamFalcon** [comment]
@c00k1ez https://gitter.im/PyTorch-Lightning/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Pull request closed without merging**
