### PR TITLE
Fix setup-doc for pypi

### LINKED ISSUE #468: Fix readme for Pypi
@Borda These lines failed to upload. Commented out for this release:
https://github.com/williamFalcon/pytorch-lightning/blob/master/setup.py#L50-L51

Please run ```twine check dist/*``` to see the issues

### PR DESCRIPTION
**Pull request by Borda**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/williamFalcon/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?
Fixes #468.

## PR review    
- Anyone in the community is free to review the PR once the tests have passed.     
- If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by williamFalcon** [comment]
@Borda the build is currently broken because of ```pip install -rrequirements.txt``` (ie: spacing issue). Where is that happening? can you fix in this PR as well?

**Comment by Borda** [comment]
@williamFalcon can you link the failing build, because checks for this PR seems to be fine...

**Comment by williamFalcon** [comment]
it's on master

**Comment by Borda** [comment]
@williamFalcon yes, you had multiple declarations of `test-tube`... fixed in 3457841

**Pull request merged**
