### PR TITLE
Hacky fix for mlflow logger

### PR DESCRIPTION
**Pull request by akhti**
It dies when "created_at" is logged

# Before submitting

- Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- Did you read the [contributor guideline](https://github.com/williamFalcon/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- Did you make sure to update the docs?   
- Did you write any new necessary tests?  

## What does this PR do?
Fixes # (issue).

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.   

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by neggert** [comment]
[According to the mlflow docs](https://mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.log_metric), `log_metric` only takes floats. It might be better to check for a float (or better yet, try to coerce to a float and catch any exceptions).

I'd also like to see a warning thrown instead of silently discarding data.

**Comment by akhti** [comment]
Added log message.

There is no typing in the code:
https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/client.py#L156
I'm pretty sure it will handle ints and numpy scalars.

**Comment by williamFalcon** [comment]
there's a blacklist of things it shouldn't log. isn't created_at one of those?

**Comment by neggert** [comment]
I guess IMO I'd still rather catch the error than try to maintain a list of types that don't work. What if a user tries to log a dict or something?

@williamFalcon You mean a blacklist in lightning somewhere?

**Comment by neggert** [comment]
Here's what MLFlow is doing to validate: https://github.com/mlflow/mlflow/blob/d744f6702c3944cdf019d668568602145b184f56/mlflow/utils/validation.py#L59. Again, though, let's just catch the exception, rather than trying to keep in sync with what they'll take as input.

**Comment by williamFalcon** [comment]
@neggert the blacklist is for lightning specific values such as batch number, epoch, etc... but yeah, your way also handles user error which is better

**Pull request merged**
